### ISSUE TITLE
[11ty] Objects are not valid as a React child

### ISSUE THREAD

**Issue by petar-v** [slinkity/slinkity#249]
## Describe the bug
Getting an error when trying to open the default starting website.

## To Reproduce
1. Run `npm init slinkity`
2. Make the following selection:
```
Need to install the following packages:
  create-slinkity@2.0.1
Ok to proceed? (y) 
✔ What is your project called? … my-slinkity-site
✔ What flavor of components do you want, if any? › Preact, Vue, Svelte, React
Welcome to your first Slinkity site!
```
3. `cd` into dir and run `npm i`
4. run `npm start`
5. try to open the webpage via the browser
6. see error in terminal, and the browser just continues to load

## Expected behavior
To be able to view the website.

## Error message

```
3:49:55 PM [vite-plugin-svelte] ssr compile in progress ...
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] Objects are not valid as a React child (found: object with keys {type, props, key, ref, __k, __, __b, __e, __d, __c, __h, constructor, __v, __source, __self, __o}). If you meant to render a collection of children, use an array instead. (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Objects are not valid as a React child (found: object with keys {type, props, key, ref, __k, __, __b, __e, __d, __c, __h, constructor, __v, __source, __self, __o}). If you meant to render a collection of children, use an array instead.
[11ty]     at mapIntoArray (some-dir/my-slinkity-site/node_modules/react/cjs/react.development.js:1037:17)
[11ty]     at mapChildren (some-dir/my-slinkity-site/node_modules/react/cjs/react.development.js:1066:3)
[11ty]     at toArray (some-dir/my-slinkity-site/node_modules/react/cjs/react.development.js:1116:10)
[11ty]     at ReactDOMServerRenderer.render (some-dir/my-slinkity-site/node_modules/react-dom/cjs/react-dom-server.node.development.js:3779:28)
[11ty]     at ReactDOMServerRenderer.read (some-dir/my-slinkity-site/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
[11ty]     at renderToString (some-dir/my-slinkity-site/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
[11ty]     at ssr (some-dir/my-slinkity-site/node_modules/@slinkity/react/ssr.cjs:13:11)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async some-dir/my-slinkity-site/node_modules/slinkity/dist/index.cjs:173:26
[11ty]     at async Promise.all (index 0)
[11ty]     at async handleSsrComments (some-dir/my-slinkity-site/node_modules/slinkity/dist/index.cjs:142:5)
[11ty]     at async EleventyDevServer.applyViteHtmlTransform (some-dir/my-slinkity-site/node_modules/slinkity/dist/index.cjs:202:28)
^C%      
```

**(please complete the following information):**
 - OS: Arch btw
 - Browser: Any browser
 - Node Version:  v20.3.0

**Comment by bholmesdev** [comment]
Thanks for the thorough reproduction @petar-v! I am sorry to say that Slinkity is no longer maintained. To make this clear to new users, I have archived the repository, and I have updated the project README to reflect the current status.

If the community would like to fork and keep Slinkity alive, all code is open and MIT licensed. I apologize for the radio silence, but I hope this clarifies everything!
